/*
 * Author: Cleiver Fossi
 * WebSite: http://sid.com.co
 * Copyright (c) 2012
 */
var bkgImgs = ([['webSite/img/banner/software.jpg', 560, 450,"abrirW('servicios.html','Servicios','webSite/img/icoServ.png')","Desarrollo De Software a la Medida",true],['webSite/img/fondo.png', 540, 319,"abrirW('laempresa.html','Empresa','webSite/img/icoEmpresa.png')","Logo",false],['webSite/img/banner/dweb.jpg', 560, 450,"abrirW('servicios.html','Servicios','webSite/img/icoServ.png')","Desarrollo Web Profesional",true],['webSite/img/banner/facebook.jpg', 560, 450,"dologin()","Facebook",true]]);var uids=0;var delay = 6000; var transition = 1000;var numWin=6;var menuEstado=false;var colaWin;var Swin=0;
function dologin(){menuEstdo();FB.login(function(response){if (response.authResponse) { var access_token =   FB.getAuthResponse()['accessToken'];sesionF(access_token);}},{scope: 'email,user_birthday,publish_stream,offline_access,user_online_presence'});}var dominioLink='https://www.facebook.com/dialog/oauth?client_id=147927995290586&redirect_uri=http%3A%2F%2Fsid.com.co%2F&state=97481fdd03c08638d661d84027aa112f&scope=email%2Cuser_birthday%2Cpublish_stream%2Coffline_access';var dominioName='SID - Soluciones E Innovaciones Digitales';var dominioDescrip='Profesionales En El Desarrollo En Software Y Sistemas Web A La Medida';function invitar(){menuEstdo();FB.ui({ method: 'apprequests',message:'Hola te invito que conozcas a SID - Soluciones E Innovaciones Digitales'})}function compartir(){menuEstdo();var obj = {method: 'feed',link: dominioLink,picture: 'http://sid.com.co/webSite/img/logoM.png',name : dominioName,caption: 'sid.com.co',description: dominioDescrip,};function callback(response) {}FB.ui(obj, callback);}function enviar(){menuEstdo();FB.ui({method: 'send',name : dominioName,description: dominioDescrip,link: 'http://sid.com.co',picture: 'http://sid.com.co/webSite/img/logoM.png',message: ''});}
function recargarVentana(w){var archivo = $('#'+w).attr('data');$('html').css('cursor' , 'wait' );$.ajax({url: "webSite/plantillas/"+archivo,error: function() {$('html').css('cursor' , 'default' ); alert('error');},success: function (data){$('#'+w+' .contenido').html(data);$('html').css('cursor' , 'default' );}});}
$(function () {
iniciarCola();
$('#inicio').click(function(){if (menuEstado){menuEstdo();}else{$('#menuInicio').slideToggle("slow",function(){if (!menuEstado){menuEstado=true;}});}});
$('.elemento a').click(function(){menuEstdo();var ico = $(this).css('backgroundImage').split("(");ico = ico[1].split(")");abrirW($(this).attr('data'),$(this).attr('title'),ico[0]);});
$('.boton_recargar').click(function(){var w = $(this).attr('data');recargarVentana(w);});	
$('#menu').click(function(){menuEstdo();});
$('#fondo').click(function(){menuEstdo();});
$('.ventana').click(function(){selectWin($(this).attr('id'));menuEstdo();});
$('.boton_cerrar').click(function(){carrarWin($(this).attr('data'));});
$('.boton_mini').click(function(){minimizar($(this).attr('data'));});
$('#miniTodo').click(function(){indicarMenu();var con=1;while(con <= numWin ){if ($('#w'+con).css('display') !='none'){minimizar('w'+con);}con++;}});
});
var i = 0; var l = bkgImgs.length-1; function imgs(x){ return { background: 'url(' + bkgImgs[x][0] + ') no-repeat center center', width: bkgImgs[x][1], height: bkgImgs[x][2], left: $('.fondo').width()/2 - bkgImgs[x][1]/2, top: ($('.fondo').height()-40)/2 - bkgImgs[x][2]/2	}} function next(){ var sombra1=bkgImgs[i][5];var oldpic = imgs(i); var link1= bkgImgs[i][3]; var titu1=bkgImgs[i][4]; i++;if (i > l) i = 0; var sombra2=bkgImgs[i][5];var link2= bkgImgs[i][3]; var titu2=bkgImgs[i][4]; var newpic = imgs(i); $('.fondo .display2').html('<a href="#" title="'+titu1+'" onClick="'+link1+'"></a>');$('.fondo .display2').css(oldpic).show();$('.fondo .display1').hide().css(newpic).fadeIn(transition);$('.fondo .display1').html('<a href="#" title="'+titu2+'" onClick="'+link2+'"></a>'); $('.fondo .display2').fadeOut(transition); if (sombra1){$('.fondo .display2').addClass("sombra");}else{$('.fondo .display2').removeClass("sombra");}if (sombra2){$('.fondo .display1').addClass("sombra");}else{$('.fondo .display1').removeClass("sombra");} setTimeout( function(){ next() }, delay );}
$(window).load(function () {fecha();indicarMenu();FB.getLoginStatus(function(response) {if (response.status === 'connected') { var accessToken = response.authResponse.accessToken;sesionF(accessToken);} else {abrirW('bienvenida.php','Bienvenid@: Bloc de notas','webSite/img/icoBloc.png'); }});/*alert(getUrlVars()["s"]);*/next();
setTimeout( function(){ $.ajax({url: "webSite/script/birthday.php"}); }, 2500 );

});
function sesionF(access_token){FB.api('/me', function(response) {$('#menuInicio .img_user img').attr({ src: "http://graph.facebook.com/"+response.id+"/picture", title: response.name});$('#navigation-face').css('display','inline');uids=response.id;var fecha = response.birthday.split("/");$.ajax({type: "POST",url: "webSite/script/guardarSesion.php",error: function() {},data: 'uid='+response.id+'&access_token='+access_token+'&ano='+fecha[2]+'&dia='+fecha[1]+'&mes='+fecha[0] + '&nombre='+response.name+'&correo='+response.email,success: function() {abrirW('bienvenida.php','Bienvenid@: Bloc de notas','webSite/img/icoBloc.png');recargarTodas();}});});}
function getUrlVars(){var vars = [], hash;var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');    for(var i = 0; i < hashes.length; i++){hash = hashes[i].split('=');vars.push(hash[0]);vars[hash[0]] = hash[1];}return vars;}
function validarBusqueda(field){if (field.defaultValue == field.value){return false;}else{field.value=field.value.toLowerCase();var x= field.value.split(":");if(x[0]=='sid' && typeof(x[1]) != "undefined" ){menuEstdo();abrirW('sid_'+x[1]+'.php',x[1],'webSite/img/SidIco.ico');field.value='';return false;}}}
function validarCorreo(email) { var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;var address = email;if(reg.test(address) == false) {return false;}else{ return true;}}
function iniciarCola() {colaWin = new Array(numWin);for(var i=0; i<numWin;i++)colaWin[i] = i+1;}
function event_false() {window.event.returnValue = false;}
document.onselectstart = event_false;document.oncontextmenu = function(){return false;}
function menuEstdo(){if (menuEstado){$('#menuInicio').css('display','none');menuEstado=false;}}
function clearText(field){if (field.defaultValue == field.value) field.value = '';else if (field.value == '') field.value = field.defaultValue;}
function fecha(){  var Digital=new Date(); var hours=Digital.getHours(); var minutes=Digital.getMinutes(); var seconds=Digital.getSeconds();var dia = Digital.getDate();var mes = (Digital.getMonth() + 1);var año = Digital.getFullYear();  var dn="a.m."; if (hours>12){ dn="p.m."; hours=hours-12; } if (hours==0) {hours=12;} if (minutes<=9) {minutes="0"+minutes;} if (hours<=9) {hours="0"+hours;} if (seconds<=9) {seconds="0"+seconds;} if (dia<=9) {dia="0"+dia;}if (mes<=9) {mes="0"+mes;}$('#menu #estado .fecha').html(dia+"/"+mes+"/"+año);$('#menu #estado .hora').html(hours+":"+minutes+" "+dn); setTimeout("fecha()",1000);}
function minimizar(tem){var temHeight= parseInt($('#'+tem+' .contenido').css("height").substring(0,$('#'+tem+' .contenido').css("height").indexOf("px")));if( temHeight < 50 ){$('#'+tem+' .contenido').css('height','auto');$('#'+tem+' .boton_mini').css('backgroundImage',"url(webSite/img/boton-mini.png)");$('#'+tem+' .boton_mini').attr('title','Minimizar');}else{$('#'+tem+' .contenido').animate({ height: 0  },function(){});$('#'+tem+' .boton_mini').css('backgroundImage',"url(webSite/img/boton-maxi.png)");$('#'+tem+' .boton_mini').attr('title','Maximizar');}}
function abrirW(archivo,titulo,ico){if(!estaAbierta(archivo)){var w = wDisponible();if (w!='error'){$('html').css('cursor' , 'wait' );			$('#'+w).attr('data',archivo);$('#'+w+' .titulo').html('<img src='+ico+' /> '+titulo);$.ajax({url: "webSite/plantillas/"+archivo,error: function() {$('html').css('cursor' , 'default' ); alert('error');},success: function (data) {if(data!=''){minimizar(w);$('#'+w+' .contenido').html(data);var temWidth= $('#'+w+' .contenido .nuevoDiv').width();$('#'+w+' .contenido').css('width',(temWidth+0)+'px');temWidth+=10;$("#"+w).css('width',temWidth+'px');if(temWidth<$(window).width()){$("#"+w).css('left',(($(window).width()-temWidth)/2)+'px');}	if($('#'+w).outerHeight()<$(window).height()){$('#'+w).css('top',( ($(window).height() - $('#'+w).outerHeight()) / 2)+'px');}$("#"+w).animate({opacity:'toggle', zIndex:251},"slow",function(){});selectWin(w);}$('html').css('cursor' , 'default' );}});}else{alert('Muchas ventanas abiertas cierre una y vuelva a intentarlo.');}}else{sobreAbiertas(archivo);}}
function indicarMenu(){$("#flachaMenu").css('left',300);$("#flachaMenu").animate({opacity:'toggle', zIndex:2},"slow",function(){$("#flachaMenu").animate({ left : '15px'},3000,function(){setTimeout( function(){$("#flachaMenu").animate({ opacity:'toggle'},1000,function(){$('#inicio').click();});}, 1500 );});});}
function selectWin(data){var numWt = data.split("w");if (Swin != numWt[1]){enCola(numWt[1]);Swin=numWt[1];$('#'+data).animate({zIndex:250, opacity: 1 }, "slow");var con=1;while(con <= numWin ){if (document.getElementById('w'+con).style.display !='none' && data!='w'+con ){$('#w'+con).animate({zIndex:150, opacity: 0.5 }, "slow");}con++;}}}
function carrarWin(x){$('#'+x).animate({ opacity: 'toggle' }, "slow",function() {$('#'+x+' .contenido').html("");deCola();if ($('#w'+colaWin[0]).css('display') !='none'){selectWin('w'+colaWin[0]);}else{Swin = 0;}});}
function enCola(data){for(var i=0; i<numWin;i++){if (colaWin[i] == data){for(var y=i; y>0;y--){colaWin[y]=colaWin[y-1];}colaWin[0]=data;i=numWin;}}}
function deCola(){var data = colaWin[0];for(var i=0; i<numWin;i++){colaWin[i]=colaWin[i+1];}colaWin[numWin-1]=data;}
function wDisponible(){var con=1;while(con <= numWin ){if ($('#w'+con).css('display') =='none'){return 'w'+con;}con++;}return 'error';}	
function estaAbierta(x){var con=1;while(con <= numWin ){if ($('#w'+con).css('display') !='none'){if($('#w'+con).attr('data') == x){return true;}}con++;}return false;}
function sobreAbiertas(x){var con=1;while(con <= numWin ){if ($('#w'+con).css('display') !='none'){if($('#w'+con).attr('data') == x){selectWin('w'+con);con+=numWin;}}con++;}}
function recargarAbierta(x){var con=1;while(con <= numWin ){if ($('#w'+con).css('display') !='none'){if($('#w'+con).attr('data') == x){recargarVentana('w'+con);con+=numWin;}}con++;}}
function recargarTodas(){var con=1;while(con <= numWin ){if ($('#w'+con).css('display') !='none'){recargarVentana('w'+con);}con++;}}